### ISSUE TITLE
Frame Limiter Suggestion

### ISSUE THREAD

**Issue by theyareonit** [McKay42/McEngine#133]
Not sure if I'm fully understanding how it works, but from what I can tell the frame limiter has 2 problems (on all platforms):
- It might relinquish the thread's remaining timeslice right at the start of a frame, slightly hurting performance
- The delayTime calculation is slightly flawed and may cause minor desync due to being based on frameTimer->getDelta() (since frameTimer->getDelta() is dependent on when frameTimer->update() was last called, which is not always going to be exactly on time, it might be slightly off sync due to various reasons such as the Sleep(0) call).

Here's an example of a frame limiter for Windows that does not suffer from these issues:
```
const double frameTime = 1.0 / (double)fps_max.getFloat();
const double delayStart = frameTimer->getElapsedTime();
const double delayEnd =  (delayStart - (delayStart % frameTime)) + frameTime; // sync frames with the time you opened the game

double delayTime = frameTime;
while (delayTime > 0.0)
{
    if (delayTime > 0.001) Sleep(0); // dont give up timeslice if less than 1ms remains
    frameTimer->update();
    delayTime = delayEnd - frameTimer->getElapsedTime();
}
```
(I haven't run it myself to test, so it may need minor changes. Also, I left out stuff related to background FPS etc. that would need to be added in).

**Comment by McKay42** [comment]
> Not sure if I'm fully understanding how it works

> from what I can tell [the frame limiter has 2 problems]

> I haven't run it myself to test

As with all things performance related, the only relevant facts are profiling data from actual testing. From what you posted it seems that you neither profiled the current build (e.g. via CTRL + F11 in-game, or external tools like Fraps + [Frafs](https://sourceforge.net/projects/frafsbenchview/)) nor your changes, so all conclusions are purely theoretical. Please try to avoid this, as it is not very productive.

> It might relinquish the thread's remaining timeslice right at the start of a frame, slightly hurting performance

This is intentional, as there are even ConVars to allow players to disable the 0 sleep (`fps_max_yield`, `fps_unlimited_yield`). It is usually massive overkill to have a pure busy loop, the 0 sleep is fine and works the same on all other relevant osu! clients (osu!stable, osu!lazer).

> The delayTime calculation is slightly flawed

No. You misunderstood the code, as the frame limiter block is a bit weird architecturally because of the timer update call order.
There is no "slightly off" or lost time, I've tried to explain this in the comment [here](https://github.com/McKay42/McEngine/blob/4ca5559c608afdabddb1449fac216584dbdbf043/McEngine/src/Engine/Main/main_Windows.cpp#L1500) but again you really have to step through the code in your head (or a debugger).

**Comment by McKay42** [comment]
Maybe this image illustrates it better:

<img width="891" alt="Capture" src="https://github.com/user-attachments/assets/36380894-b92f-4e66-b17e-0f04549ce3e0">

**Comment by McKay42** [comment]
For the initial iteration, the time between the start of the frame limiter block and the while loop inside is integrated in `delayStart`, so nothing lost there, as accurate as you can possibly be. Then once inside the while loop it's business as usual, we measure every iteration how long the e.g. `Sleep(0)` took and respect that in the `delayTime` for the next iteration.

**Comment by theyareonit** [comment]
I agree that full sleepless is unnecessary, but I don't see what sleepless for the last 0.1ms or so before the next frame would hurt. It makes sense to always sleep at least once if running unlimited FPS or if you're lagging, but in this case, you already would've slept earlier in the waiting process and given time for background tasks to run (i.e. `didSleep` would be `true`).

And you're correct that I probably should've debugged it myself rather than looking through the code; however, I still don't quite see what you mean with regard to the delayTime calculation. What I'm referring to here is the initial delayTime calculation at the start of the frame: the line `delayTime = (1.0 / (double)fps_max.getFloat()) - frameTimer->getDelta();`. The thing is that getDelta here is relative to the last time frameTimer->update() was called, but this is not going to be exactly at the start of the frame, it's going to be a little bit after the frame started.

![image](https://github.com/user-attachments/assets/78b919b9-bb96-46fb-8c80-5e11c2f5ccf4)

Here's a diagram to illustrate what I mean. `fps_max - getDelta()` is always going to be just a little bit more than is necessary, since the last call to frameTimer->update() wasn't on the ideal frame boundary, but a little bit after it. If I understand correctly, this will cause slight desync over time. In practice this doesnt make a large difference (I still get 1439fps when I have a 1440fps cap, and that may just be due to inaccuracy in the way FPS is measured), but it could make more of a difference if you have any background tasks competing for CPU time at the wrong moment.

To account for this, I would think you would need to either add the previous frame's delayTime (which would be slightly less than 0) to the new delayTime value, or do some modulo shenanigans like I did.

**Comment by McKay42** [comment]
> but I don't see what sleepless for the last 0.1ms or so before the next frame would hurt

I agree, will add a ConVar at some point to allow customizing the delta for "don't 0 sleep if we are _almost_ ready for the next frame". I think I've instinctively tried to avoid any branching in the busy while loop, but it should be fine even if ConVars use an `std::atomic<float>` to `.load()` instead of a primitive `float` for the comparison value (as atomics should be more or less free to read). This will need jitter testing to confirm it is actually better overall though. On my system, the average busy loop iteration delta is ~300 nanoseconds with +-100 nanoseconds jitter in the current implementation.

> but this is not going to be exactly at the ideal frame start time

> fps_max - getDelta() is always going to be just a little bit more than is necessary

The time block for the delayTime is always measured like this:

<img width="343" alt="main_loop2" src="https://github.com/user-attachments/assets/0d269a0d-4cb8-4425-8c7a-6b534c09c6b1">

Everything between the last `frameTimer->update()` call from inside the busy while loop up to the `frameTimer->update()` call at the beginning of the fps limiter block is accounted for, including the extra `Sleep(0)` before every frame. If the delayTime is slightly negative at the end, then this is accounted for in the next iteration delta so it averages out to 0 across frames (source of microsecond jitter of course, too small to be relevant at all though).

> To account for this, I would think you would need to either add the previous frame's final delayTime value (which would be slightly less than 0) to the new delayTime value

As mentioned above this already happens. Maybe the source of confusion?

> In practice this doesn't make a large difference

Correct

> but it could make more of a difference if you have any background tasks competing for CPU time at the wrong moment

If you get hard stalled by the OS scheduler then there is nothing you could have done (you already have the lag spike, nothing really matters anymore for that single frame). This should never be a problem on modern OSs, as anything using 3D graphics APIs will get prioritized usually (game mode etc.). If you have any concrete practical examples where this _actually_ becomes a problem then maybe?

> I still get 1439fps consistently when I have a 1440fps cap

(Generally I only consider fps limiter values up to 1000 fps valid and useful, anything higher is **not** supported/intended by the limiter logic (also not tested/validated by me).)

**Comment by theyareonit** [comment]
> Everything between the last frameTimer->update() call from inside the busy while loop up to the frameTimer->update() call at the beginning of the fps limiter block is accounted for [...] If the delayTime is slightly negative at the end, then this is accounted for in the next iteration delta so it averages out to 0 across frames

I don't really see where the final delayTime value is accounted for though? getDelta() measures the time in between the most recent call to update() and the call before that. However, this is essentially just the [simulation + render] time. If the final call to update() in the loop is delayed (i.e. delayTime is negative), then there's nothing to correct for it, since that's not included in the [simulation + render] time.

![image](https://github.com/user-attachments/assets/73da90d1-4da1-4ef5-ba0d-d030cb265f2b)

When I mentioned the Sleep(0) call as a potential source of issues here, I didn't mean the one outside the loop, I meant the final call within the loop, right before the final call to frameTimer->update(). The stuff outside of the loop is accounted for by getDelta(), but anything that happens after the start of the while loop--but before the final call to update()--isn't.

**Comment by McKay42** [comment]
I think I know what this is now, you know how there are two separate timers yes? The `frameTimer` is purely for the fps limiter, while the `deltaTimer` is what the simulation uses (such that no matter what the limiter does, simulation time is measured correctly as close to the update call site as possible).

If a frame oversleeps in the fps limiter due to some driver acting up, then _that's the only thing that happens_, you get to the next frame slightly later (What else could happen? Nothing else.). Simulation time is measured separately via `deltaTimer` and correctly integrates the extra delay because of that. There is no problem here?

**Comment by theyareonit** [comment]
> If a frame oversleeps in the fps limiter due to some driver acting up, then that's the only thing that happens, you get to the next frame slightly later (What else could happen? Nothing else.).

Yeah, it shouldn't affect game logic. But what it could cause is a rolling tearline, when otherwise someone would have a static tearline (e.g. my monitor is exactly 360.000hz, so capping my FPS to a multiple of 360 should in theory result in an almost perfectly stationary tearline, but in this case it would slightly move across the screen due to the desync). Not a big deal, just a microoptimization that could be made.

**Comment by McKay42** [comment]
> But what it could cause is a rolling tearline

You mean because of the extra `Sleep(0)` calls? As otherwise it would be identical to your frame limiter.

**Comment by theyareonit** [comment]
Because of any factor that could cause delayTime to be negative, which could be giving up the thread's timeslice at the wrong time, an interrupt, the time it takes to execute frameTimer->update() (even though this would be negligible), etc.

(also, technically my frame limiter would behave slightly differently if you lagged by more than 1 frame, it would just drop the frame entirely rather than starting a new frame immediately)

**Comment by McKay42** [comment]
Yes, but how is your frame limiter better in any way? You could oversleep just the same and also get to the next frame late.

**Comment by McKay42** [comment]
Besides fixed tearlines I don't really see any other usecase, would be interesting to know which method different games all implement and which is the most common one.

**Comment by theyareonit** [comment]
Not really sure about AAA games, but this is how it is in the code of games I've taken a look at:
- osu!lazer: Fully sleep based, tries to "catch up" if you drop frames by essentially switching to unlimited FPS when you lag. I don't know if this actually helps much with smoothness or if it just artificially inflates the FPS counter.
- Minecraft: Essentially the same as McOsu, although some part of it is poorly implemented and causes you to average ~237fps if you have a 240fps cap. It also sleeps more aggressively (e.g. actually sleeping for most of the duration of the frame rather than just giving up the thread's timeslice in a loop)
- Geometry Dash: Fully busy wait, uses the same algorithm as what I suggested (this is where I copied it from)
