### ISSUE TITLE
Segmentation Fault on launch

### ISSUE THREAD

**Issue by jimgao1** [McKay42/McEngine#74]
Running the latest version of McOsu from Steam (Version 30.11) on Arch Linux 5.3.6-arch1-1-ARCH.

The McEngine binary segfaults on launch. When tried to run it with gdb, it appears that the program crashed on a call to __strlen_avx2 () from /usr/lib/libc.so.6. 

Below is the screenshot:
![Screenshot from 2019-11-18 21-50-47](https://user-images.githubusercontent.com/6977171/69112339-f822a100-0a4d-11ea-9841-911561e4dd45.png)

Thanks so much!

**Comment by McKay42** [comment]
I've now tested this with 5.1.4-arch1-1-ARCH and 5.3.11-arch1-1 (after manual pacman upgrade), and it worked just fine, inside a virtual machine at least.

Can you upgrade to at least 5.3.11 and try it again?

Your setup crashes way too early, maybe even before main(), since not a single thread was created, suggesting that it is caused by the environment rather than the game (not 100% sure ofc since it could theoretically crash while initializing global variables/convars).
Normal startup should look like this:
```
(gdb) run
Starting program: /home/<USERNAME>/.local/share/Steam/steamapps/common/McOsu/McEngine
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeda6a700 (LWP 9747)]
[New Thread 0x7fffed269700 (LWP 9747)]
[New Thread 0x7fffeca68700 (LWP 9747)]
[New Thread 0x7fffdffff700 (LWP 9747)]
-= Engine Startup =-
McEngine v4 - Build Date: Nov 15 2019, 11:17:10
...
```

**Comment by jimgao1** [comment]
Updating the system to 5.3.12 still did not fix the issue. I suspect it's something related to nvidia. Is there anyway to confirm this?

**Comment by jimgao1** [comment]
It is not a nvidia problem. I tried running it with integrated graphics and it crashes like before. 

I was able to get it to work by running an older version (possibly 2 versions behind but I do not recall exactly).

**Comment by McKay42** [comment]
This was caused by
```
char *resourceString = XResourceManagerString(m_display);
XrmDatabase db = XrmGetStringDatabase(resourceString);
```
in LinuxEnvironment.cpp

Apparently some distributions just return null for XResourceManagerString(), which if unchecked will cause libc strlen() to segfault in XrmGetStringDatabase().

Should be fixed with the latest build from yesterday.

**Comment by jimgao1** [comment]
Works now. Thanks so much!
